### ISSUE TITLE
[1.11+] Can't open world after placing a Satellite Controller

### ISSUE THREAD

**Issue by EmosewaPixel** [MJRLegends/Planet-Progression#1]
### Description of Issue
 I had a few Satellite Controllers working and everything was fine. However, after exiting my world I couldn't re-open it due to an erroring tile entity crash.

### Steps to Reproduce Issue
1. Place down a Satellite Controller
2. Exit your world
3. Re-enter your world

**Crash log/Log (if applicable):** https://pastebin.com/kftWurga

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.0

**Where did this bug happen:** Single Player

**Comment by MJRLegends** [comment]
Yeah thanks i found this in my testing, i will add a fix for next update

**Comment by MJRLegends** [comment]
Will be out later on today

**Comment by EmosewaPixel** [comment]
Oh, nice. And thanks for the quick reply.

**Comment by MJRLegends** [comment]
@EmosewaPixel No problem, any more issues let me know :D

**Comment by EmosewaPixel** [comment]
Would you care to join my discord server? https://discord.gg/vypdbxy

**Comment by MJRLegends** [comment]
Updates are currently rolling out as we speak, please give them a short while for them to show on Curseforge

**Comment by MJRLegends** [comment]
Updates are waiting on approval by curseforge
