### ISSUE TITLE
[1.11+] Nasa workbench crashes when putting rocket parts

### ISSUE THREAD

**Issue by ElSaam** [MJRLegends/Planet-Progression#10]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Crash when crafting Satellite Rocket

### Steps to Reproduce Issue
1. Try to place items in Satellite Rocket recipe GUI 

**Crash log/Log (if applicable):** https://pastebin.com/qs1vqAbd

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.1.4

**Where did this bug happen:** Both

**Comment by MJRLegends** [comment]
You have ignored this please fill it out and i will reopen
```

### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

```

**Comment by MJRLegends** [comment]
Also make sure to put the version like [1.12.2] in the title or i will have to close it too

**Comment by MJRLegends** [comment]
Updated versions have been uploaded they will show on curseforge once they have been approved, thanks for the bug report too but make sure to see my comments above before posting any future issues @ElSaam

**Comment by ElSaam** [comment]
Sorry, i'll make sure that next time i'll fill everything. Thanks anyway for the fix!
