### ISSUE TITLE
1.12.2 0.1.5 Server - Crash when typing /addNewSatellite

### ISSUE THREAD

**Issue by ElSaam** [MJRLegends/Planet-Progression#11]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
I was going to link my satellite with /addNewSatellite from server console but then server crashed after typing it.

### Steps to Reproduce Issue
1. [First step] Launch satellite rocket with basic satellite
2. [Second step] type /addNewSatellite in server

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC https://pastebin.com/6985Rxua

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 0.1.5

**Where did this bug happen:** [Single Player or Server] Server

### Additional Information
[Any other information that may be able to help me with the problem]
Doesn't happen in singleplayer and satellite has been linked after server up again.

**Comment by MJRLegends** [comment]
This command is for testing and debug/server admin use you dont link anything for survival use

**Comment by MJRLegends** [comment]
And also the command needs to ran from a player not server console

**Comment by ElSaam** [comment]
The satellite controller couldn't find my satellite until i did that command and my friends don't have permission so i have to type it for them

**Comment by MJRLegends** [comment]
Thats not how the comamnd works, this is intended use too just i will stop it crashing and tell the user to run from a player not console

**Comment by ElSaam** [comment]
Also could you make it work without needing op?

**Comment by MJRLegends** [comment]
No its not for survival use

**Comment by MJRLegends** [comment]
Thanks for the bug report but none of the commands need to be used for survival use and i will fix the server console use crahsing since its a player runable command
