### ISSUE TITLE
Telescope not researching the last planet/moon thats left to unlock

### ISSUE THREAD

**Issue by TheRealM18** [MJRLegends/Planet-Progression#13]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
The telescope stops at the last research paper that is needed to unlock/discover all planets and moons 

### Steps to Reproduce Issue
1. Research all planets and moons in till the last one
2. Place the last research paper in the telescope
3. It sits at 0% and doesnt unlock the planet/moon

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
http://prntscr.com/ijzyj3

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
PlanetProgression-1.12.2-0.1.6.jar

**Where did this bug happen:** [Single Player or Server]
Server

**Comment by MJRLegends** [comment]
Please can you explain this in more detail as im confused as the title says something about a creative tab and then the issue report doesnt mention that?

**Comment by MJRLegends** [comment]
It seems a very vague issue report

**Comment by TheRealM18** [comment]
I was testing to see how many planets there are and all of a sudden the telescope rejected the planets that I was continuing with.  The Researches stopped about half way though.

**Comment by MJRLegends** [comment]
Please edit your issue to explain this fully and with screenshots

**Comment by TheRealM18** [comment]
I really don't know how to explain without a video or something because it is a really weird bug in a sence

**Comment by MJRLegends** [comment]
Your issue says about something different from your title. Please post screenshots and actual steps for the issue as words like denied doesnt correspond to what the mod is

**Comment by MJRLegends** [comment]
I will reopen when its been edited

**Comment by MJRLegends** [comment]
Please edit this detail in your first post for the issue report with screenshots of when it gets stuck

**Comment by TheRealM18** [comment]
https://drive.google.com/open?id=1VPRLqT55MgbK26LcJ-o2Aq2Jo-H7nrpq this is the player file

**Comment by MJRLegends** [comment]
Problem solved it wasnt able to research the last planet/moon that exists

**Comment by MJRLegends** [comment]
You could use the following command to unlock this planet or moon in till the update

**/unlockCelestialBody <player> <celestialBodyName>** - Used to unlock the specified planet or moon for the player specified
