### ISSUE TITLE
[1.8+] Telescope not working with non english languages

### ISSUE THREAD

**Issue by b0bst3r** [MJRLegends/Planet-Progression#14]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Discover with the telescope dont work, if you are playing in German
Example:
Got the Paper for Moon from the Controller, telescope can't find. Same for Neptun.
Uranus and Saturn works.
Research Name: Moon Translated Name: Mond -> Doesnt discover
Research Name: Neptun Translated Name: Neptune -> Doesnt discover
Research Name: Uranus Translated Name: Uranus -> discover
Research Name: Saturn Translated Name: Saturn -> discover

After switching language to eng it discovers all. So is an issue with the Translation

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

**Where did this bug happen:** [Single Player or Server]

### Additional Information

Issue reported to MSB3 github - https://github.com/EmosewaPixel/Modern-Skyblock-3/issues/190

**Comment by MJRLegends** [comment]
Please update to latest planet progression im pretty sure your issue has been fixed if not please fill out the template fully

**Comment by MJRLegends** [comment]
Versions have been uploaded to fix this issue
