### ISSUE TITLE
[1.12.2] Issues With Research Papers

### ISSUE THREAD

**Issue by EmosewaPixel** [MJRLegends/Planet-Progression#18]
### Description of Issue
 Here are the main 3 issues with Research Papers:
- [ ] The order. With ExtraPlanets installed, this is how it begins: Moon, Neptune, Uranus, Saturn, Jupiter, Mercury, Triton, Titania, Titan, Rhea, Phobos, Oberon, Nix, Io, Iapetus, Hydra, Ganymede, Europa, Dysnomia, Deimos, Charon, Callisto, Xovis,... After the Moon, they go opposite of the order of the papers in JEI (the order is in the screenshots). I have had many people complain about not being able to go to Mars.
- [ ] Duplicating Research Papers (at least in JEI). One of the duplicates doesn't get used up in the Telescope.
- [ ] Some broken localization (although it might be on Extra Planets' side

**Screenshots (if applicable):** 
1.
![image](https://user-images.githubusercontent.com/25333164/37877509-a196d7b0-305c-11e8-9938-880960ef1017.png)
![image](https://user-images.githubusercontent.com/25333164/37877510-a548f3ac-305c-11e8-9a3b-85316c8aedfe.png)
![image](https://user-images.githubusercontent.com/25333164/37877512-a7f43a30-305c-11e8-9601-4d8158c5a802.png)
![image](https://user-images.githubusercontent.com/25333164/37877513-aab46a4c-305c-11e8-98ec-5b8c08e74dac.png)
![image](https://user-images.githubusercontent.com/25333164/37877514-acbce4b8-305c-11e8-83a3-df7df5388c66.png)
2.
![image](https://user-images.githubusercontent.com/25333164/37877517-c69425f4-305c-11e8-8201-3fd5d5f8b89a.png)
![image](https://user-images.githubusercontent.com/25333164/37877519-c9f4c8d4-305c-11e8-87ad-791bfb3db330.png)
3.
![image](https://user-images.githubusercontent.com/25333164/37877523-e3775ef2-305c-11e8-9db1-07a536b0dc20.png)
![image](https://user-images.githubusercontent.com/25333164/37877525-e6e8524e-305c-11e8-8a8d-84dabcc73d3b.png)

**Version of Mod using:** 1.12.2-0.1.8

**Where did this bug happen:** SP

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak :D
