### ISSUE TITLE
[1.12.2] Snow can pile up on the bottom of Telescopes

### ISSUE THREAD

**Issue by EmosewaPixel** [MJRLegends/Planet-Progression#19]
### Description of Issue
The title is quite self-explanatory.

### Steps to Reproduce Issue
1. Place a Telescope in a cold biome
2. Set weather to rain
3. Wait a while

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/25333164/38321122-ef8e9ae8-3836-11e8-908f-fa88c963b0f2.png)

**Version of Mod using):** 1.12.2-0.2.0

**Where did this bug happen:** Single Player and Server

**Comment by EmosewaPixel** [comment]
You still prevented it from piling up on the top block though, right?

**Comment by MJRLegends** [comment]
Yeah

**Comment by MJRLegends** [comment]
Update will be out within the next few hours :D

**Comment by MJRLegends** [comment]
Update has been uploaded and submitted just waiting on approval

**Comment by MJRLegends** [comment]
Update has been approved
