### ISSUE TITLE
[1.11+] Browsing the Nasa Workbench crashes the game

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/Planet-Progression#2]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Browsing the Nasa Workbench crashes the game (Log says something about ContainerSchematicSatelliteRocket)

### Steps to Reproduce Issue
1. Place a Nasa Workbench and click next in a New world

**Crash log/Log (if applicable):**
https://pastebin.com/sygLKpDr

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.1

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/8sb1cg0H

**Comment by MJRLegends** [comment]
Thanks for the bug report versions are rolling out now to fix this

**Comment by MJRLegends** [comment]
Updates are waiting on approval by curseforge

**Comment by MJRLegends** [comment]
All been approved now
