### ISSUE TITLE
[1.12.2] Planet Celestial Selection screen stuck with no earth

### ISSUE THREAD

**Issue by Nullga** [MJRLegends/Planet-Progression#21]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
I'm on a server. When I launched tier 1 rocket, the celestial selection screen opened up but no reachable planets/moons are there. Xenos 157 is selected as default. Even no Earth or milky way. This could be a duplicated issue of https://github.com/MJRLegends/Planet-Progression/issues/17. The server runs Modern Skyblock 3. I tried to reproduce the issue on my local server with only GC and your mods installed but it doesn't happen. I found some users on Reddit reported the same issue though no solutions have been posted as of now. I appreciate if you can take a look into. Thanks.
### Steps to Reproduce Issue
1. [First step]
Lanuch tier 1 rocket
2. [Second step]
N/A

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
https://imgur.com/a/72B4gyo
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
PlanetProgression-1.12.2-0.2.0
MJRLegendsLib-1.12.2-1.1.3
MicdoodleCore-1.12.2-4.0.1.166
GalacticraftCore-1.12.2-4.0.1.166
Galacticraft-Planets-1.12.2-4.0.1.166
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Update to latest version please

**Comment by Nullga** [comment]
Ah, okay it sounds like you've done some changes on the latest version. We'll see.

**Comment by MJRLegends** [comment]
Always test with latest version before posting any bugs. As bugs in older versions could not be in latest and we cant be worrying about older versions without knowing if the latest still has the issue

**Comment by MJRLegends** [comment]
Let me know if its still a issue with latest planet progression and if you can supply the logs that would save time very much if i have to track down the issue

**Comment by Nullga** [comment]
I'd say the same if I were a developer. Sorry to bother you but it's hard to get thru the way. I will ask the pack owner to remove the mod. Thanks anyway.

**Comment by MJRLegends** [comment]
You dont need to remove it, just please throw in the latest planet progression to the pack and test for me and if it still happens please provide me the server and client logs so i can see whats going on and see if any errors happen

**Comment by Nullga** [comment]
I'll do my best. However I like the concept of your mod at lot. I'm just curious if it's possible to add EXIT button to the screen by any chance?

**Comment by MJRLegends** [comment]
Clicking the overworld or the planet that you launch already does that a extract purpose just so happens your getting a bug you can get the server owners to edit your player file as theres a Boolean value saved in there i believe to if your in the planet screen

**Comment by MJRLegends** [comment]
Any chance you can please link me to where you saw the reddit posts?

**Comment by MJRLegends** [comment]
Please get the server owner to post the server log in this issue or contact me

**Comment by Nullga** [comment]
Okay I'll ask when he's up. It's 4am in our area right now.

**Comment by Nullga** [comment]
fml-server-latest.log? Btw the we get the screen opens right away and stuck when logging in to the server, restarting both clients and the server don't cancel it. I'll post a log as soon as possible.

**Comment by MJRLegends** [comment]
Yeah thats the log file and yeah see one of my comments above about how to fix that

**Comment by Nullga** [comment]
I'll let him know and upload the log when available. Thanks for your help.

**Comment by MJRLegends** [comment]
If you can try to get them to test with latest as that would mean the mod will be up to date and using latest code and bug might not exist now

**Comment by Nullga** [comment]
You won't believe but it's the most hard part **for me. None of your fault at this point but I'm really in the middle. I guess I should build my own pack tho. Sorry for any inconveniences.

**Comment by MJRLegends** [comment]
@Nullga No need to be in the middle or sorry. Its not your fault, the fact thats its not happening on your local server and so far no reports from anyone else getting the same issue means thats its probably something to do with that certain server.

Just forward the bug to the server owner with the message to try latest mod version and give him this issue link and we can go from there

**Comment by Nullga** [comment]
I'll so. Let's see what he got. I'll be back later on.

**Comment by thelapisfox** [comment]
I am having this issue on a SSP pack. You can see the bug and information I posted in micdoodle8/Galacticraft#3368 If you need anything regarding it, let me know.

**Comment by MJRLegends** [comment]
Yeah @thelapisfox i need your logs otherwise i can't look at it

**Comment by MJRLegends** [comment]
I cant reproduce this at all, so im going to need more information and someone to give me steps to reproduce it, i need a set of server and client logs please...

**Comment by MJRLegends** [comment]
@Nullga @thelapisfox i made some changes please try v0.2.3 i just released :D

**Comment by thelapisfox** [comment]
The issue began at 08:41:29. This part of the log is when I got into the rocket on the space station in orbit of the overworld and launched. After that, I was stuck on the screen as shown in the screenshot. I also backed up the save before overwritting it with a backup. If you want that as well, let me know.

[2018-04-28-4.log](https://github.com/MJRLegends/Planet-Progression/files/1958488/2018-04-28-4.log)

**Comment by MJRLegends** [comment]
Ok if anyone gets this issue with new ExtraPlanets let me know and i will reopen this

**Comment by saytheb** [comment]
Ran into this issue with PP 0.2.3, GC 1.176 (Modern Skyblock version 3.4). Screenshot of window, logs attached. Launched from a new space station w/ a Tier 1 rocket, fully loaded on fuel, no storage space on rocket, Sol's list is empty..

![image](https://user-images.githubusercontent.com/4807632/40160174-a139c198-5969-11e8-9c78-e17416d2cbd6.png)

[latest - client.log](https://github.com/MJRLegends/Planet-Progression/files/2011860/latest.-.client.log)

I don't see any errors or even debug IO in the server logs (latest or debug). let me know which logs you may want as Debug is 23MB so github won't let me attach.

Help me MJRLegends, you're my only hope. ;)

**Comment by ConcatenatedNonsense** [comment]
Getting this issue on Modern Skyblock 3 v3.4.1.1, any attempt to launch a Tier 1 rocket from a space station leaves me stuck in the galactic star map with no access to any commands, chat, I cannot press the escape key, and there are no planets to launch to:

![image](https://user-images.githubusercontent.com/2005090/44006742-68967946-9e81-11e8-833d-b6bf7fa83eac.png)

**Comment by MJRLegends** [comment]
@ConcatenatedNonsense please open a new issue
