### ISSUE TITLE
[1.12.2] Crash when Clicking Satellite

### ISSUE THREAD

**Issue by Truhard** [MJRLegends/Planet-Progression#22]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
In the Galaxy Catalog, clicking on the satellite orbiting Earth crashes the game. After this, you get stuck in a crash loop that can only be broken by deleting the player data.

### Steps to Reproduce Issue
1. Launch the satellite rocket into orbit.
2. Fly into space with a rocket.
3. When the catalog/map is opened, click on Earth, then on the satellite orbiting it.
4. Crash.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/YHVaBBgf

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [ExtraPlanets-1.12.2-0.3.7, PlanetProgression-1.12.2-0.2.3, MJRLegendsLib-1.12.2-1.1.4]

**Where did this bug happen:** [Single Player or Server]
SMP and SSP

### Additional Information
~~I'm talking to you right now!~~

**Comment by MJRLegends** [comment]
Updating ExtraPlanets & GC & Planet Progression will fix this issue
