### ISSUE TITLE
[1.8+] Incorrect info from tooltip on telescope battery slot

### ISSUE THREAD

**Issue by TheQuadShot** [MJRLegends/Planet-Progression#23]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**
Telescope battery slot tool tip states "Battery slot, place battery here or use a connected power source"
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes, related: https://github.com/MJRLegends/Planet-Progression/issues/20
### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
https://imgur.com/a/9k6KhaL

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
PlanetProgression-1.12.2-0.2.4
**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]33

Is there a forum or place to ask questions and make requests for this mod?

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak
