### ISSUE TITLE
Request for Satellite Builder Automation of input/output of items

### ISSUE THREAD

**Issue by Moobien** [MJRLegends/Planet-Progression#24]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

Hey, just a request. can the satellite builder be made to be able to have items pumped in and out of them please.

**Comment by MJRLegends** [comment]
Sorry for the delay, but im going to be adding this feature in for the next update :D

**Comment by MJRLegends** [comment]
Update will be out later on today/early tomorrow containing this :D
