### ISSUE TITLE
Satellite item is not consumed after launching rocket

### ISSUE THREAD

**Issue by billybob884** [MJRLegends/Planet-Progression#25]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

### Description of Issue
If you load your satellite into the satellite rocket's cargo and stay inside the satellite rocket while launching it, after you are ejected at the top of the world (Y=1200), you get your satellite and (nearly) all your fuel back in the parachest.

### Steps to Reproduce Issue
1. Build a fuel satellite rocket
2. Enter satellite rocket (I had a parachute, O2 gear, O2 mask, and 2 O2 tanks equipped)
3. Put satellite into satellite rocket's cargo
4. Stay inside rocket and launch
5. At y=1200, you are ejected from the rocket, your parachute deploys and you fall, and at the same time a parachest is created, with the satellite you put in the rocket's cargo, as well as ~1200 fuel

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
N/A - No crash

**Screenshots (if applicable):** 
https://imgur.com/a/Z291cH8

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
PlanetProgression-1.12.2-0.2.3

**Where did this bug happen:** 
Single Player

### Additional Information
The satellite is still successfully launched, it shows up in the satellite controller, and it researches the moon (or whatever planet is next to be researched).

**Comment by MJRLegends** [comment]
Please test with latest version and i will reopen once you confirm its still a issue also update GC and any other Galacticraft addons you have

**Comment by billybob884** [comment]
With a fresh install of Minecraft, using Forge version 1.12.2-14.23.4.2707, this is still an issue. I have the following mods installed:
ExtraPlanets-1.12.2-0.3.8
GalacticraftCore-1.12.2-4.0.1.177
Galacticraft-Planets-1.12.2-4.0.1.177
MicdoodleCore-1.12.2-4.0.1.177
MJRLegendsLib-1.12.2-1.1.4
OptiFine_1.12.2_HD_U_D3
PlanetProgression-1.12.2-0.2.4

**Comment by MJRLegends** [comment]
Thanks i dont know how this is like this and i didnt know but glad its found better late than never i suppose haha

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak
