### ISSUE TITLE
Telescope power drains too quick to research

### ISSUE THREAD

**Issue by billybob884** [MJRLegends/Planet-Progression#26]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

### Description of Issue
When placing a battery in the telescope, the battery fills the telescope, but it does not retain this power for more than a few seconds, even when not in use. It is impossible to fill the telescope's power meter.

### Steps to Reproduce Issue
1. Build standard telescope & standard Galacticraft battery (holds 15,000gJ of energy)
2. Put battery in telescope (without any research paper)
3. Telescope will drain battery, partially filling it's energy meter in ~4 seconds
4. Telescope's energy meter will drain to empty after ~4 more seconds

**Crash log/Log (if applicable):**
N/A - No crash

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
PlanetProgression-1.12.2-0.2.3

**Where did this bug happen:**
Single Player

### Additional Information
Is there a specific type of battery we're supposed to use? There doesn't seem to be a connection point to wire power directly (why is this?)

**Comment by MJRLegends** [comment]
Please test with latest version and i will reopen once you confirm its still a issue also update GC and any other Galacticraft addons you have

**Comment by billybob884** [comment]
With a fresh install of Minecraft, using Forge version 1.12.2-14.23.4.2707, this is still an issue. I have the following mods installed:
ExtraPlanets-1.12.2-0.3.8
GalacticraftCore-1.12.2-4.0.1.177
Galacticraft-Planets-1.12.2-4.0.1.177
MicdoodleCore-1.12.2-4.0.1.177
MJRLegendsLib-1.12.2-1.1.4
OptiFine_1.12.2_HD_U_D3
PlanetProgression-1.12.2-0.2.4

**Comment by MJRLegends** [comment]
This is intended but whats not intended is that it resets the progress when it runs out of power which i've fixed for the next update so i will just stop at the % it gets to when it runs out of power and then you can add more power to get it going again. You can always use the ExtraPlanets batteries for bigger power storage or the Atomic battery from GC

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak
