### ISSUE TITLE
Telescope "Disable" button does not work

### ISSUE THREAD

**Issue by billybob884** [MJRLegends/Planet-Progression#27]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

### Description of Issue
When pressing the "disable" button on the telescope, the telescope does not stop researching (and still consumes power).

### Steps to Reproduce Issue
1. Build standard telescope & standard Galacticraft battery (holds 15,000gJ of energy)
2. Put research paper in telescope
3. Press telescope's "disable" button
4. Put battery in telescope. Telescope will still research and drain battery

**Crash log/Log (if applicable):**
N/A - No crash

**Screenshots (if applicable):** 
https://imgur.com/a/8akYH7R

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
PlanetProgression-1.12.2-0.2.3

**Where did this bug happen:**
Single Player

**Comment by MJRLegends** [comment]
Test with latest and i will reopen once you confirm its still a issue also update GC and any other Galacticraft addons you have

**Comment by billybob884** [comment]
With a fresh install of Minecraft, using Forge version 1.12.2-14.23.4.2707, this is still an issue. I have the following mods installed:
ExtraPlanets-1.12.2-0.3.8
GalacticraftCore-1.12.2-4.0.1.177
Galacticraft-Planets-1.12.2-4.0.1.177
MicdoodleCore-1.12.2-4.0.1.177
MJRLegendsLib-1.12.2-1.1.4
OptiFine_1.12.2_HD_U_D3
PlanetProgression-1.12.2-0.2.4

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak
