### ISSUE TITLE
[1.12.2] Console Spam when hovering over specific Research Papers

### ISSUE THREAD

**Issue by MasterEnderman** [MJRLegends/Planet-Progression#28]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

yes

### Description of Issue
If you have one of the following Research Papers:

- Eris
- Ceris
- Kuiper Belt
- Pluto

in your inventory and hover over them with the cursor,
the console will constantly filled with the following message:

```
[02:53:09] [main/FATAL] [com.mjr.mjrlegendslib.util.MessageUtilities]: mjrlegendslib: Ceres
[02:53:09] [main/FATAL] [com.mjr.mjrlegendslib.util.MessageUtilities]: mjrlegendslib: Eris
[02:53:09] [main/FATAL] [com.mjr.mjrlegendslib.util.MessageUtilities]: mjrlegendslib: Kuiper Belt
[02:53:09] [main/FATAL] [com.mjr.mjrlegendslib.util.MessageUtilities]: mjrlegendslib: Pluto
```

### Steps to Reproduce Issue
1. Put one of the Research Papers in your Inventory
2. Hover over them with the cursor

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

Console/Log: https://pastebin.com/Y3gESKGY

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

Forge: 14.23.4.2712
MicdoodleCore: 4.0.1.177
GalacticraftCore: 4.0.1.177
GalacticraftPlanets: 4.0.1.177
MJRLegendsLib: 1.1.4
More-Planets: 2.1.2
MorePlanetsExtras: 1.0
ExtraPlanets: 0.3.9
Planet Progression: 0.2.5

**Where did this bug happen:** [Single Player or Server]

Singleplayer

**Comment by MJRLegends** [comment]
Sorry must of missed your issue. I will fix thanks

**Comment by MJRLegends** [comment]
I've posted this over at MJRLegendsLib for me to fix there as the output message is in that mod :D https://github.com/MJRLegends/MJRLegendsLib/issues/7
