### ISSUE TITLE
[1.12.2] Change satellite rocket to be like the cargo rocket from Galacticraft [Request]

### ISSUE THREAD

**Issue by DJJBanx** [MJRLegends/Planet-Progression#29]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

In Galacticraft the cargo rocket does not require you to be in the rocket and can be launched without you being in the rocket. Why does the satellite rocket require you to be in the actual rocket as it launches? I shift-ed out of the rocket as it launched and it did not send a satellite to space, and did not drop a parachest with the items (rocket and fuel) in it. My request is to make the rocket like the cargo rocket or (if the former requires too drastic of a re-write) to at least allow you to simply get in the rocket and shift out of it while it launches so that you don't have to fly all the way up in the rocket to launch the satellite.

Forge: 14.23.4.2708
Micdoodle-Core: 4.0.1.181
Galacticraft-Core: 4.0.1.181
Galacticraft-Planets: 4.0.1.181
MorePlanets: 2.0.15-GC181
PlanetProgressions: 0.2.5

**Comment by MJRLegends** [comment]
This is intended due to how the code works for the satellite

**Comment by MJRLegends** [comment]
I'll keep the comments in mind though thanks
