### ISSUE TITLE
[1.10+] Satellite builder doesn't consume the right amount of satellite modules

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/Planet-Progression#3]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Satellite Builder needs 6 basic satellite modules to start crafting a satellite, but only consumes 1.

### Steps to Reproduce Issue
1. Craft a satellite in satellite builder

**Crash log/Log (if applicable):**
No crash

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.1

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/8sb1cg0H

**Comment by MJRLegends** [comment]
Thanks for the bug report versions are rolling out now to fix this

**Comment by MJRLegends** [comment]
Updates are waiting on approval by curseforge

**Comment by MJRLegends** [comment]
All been approved now
