### ISSUE TITLE
[1.12.2] Allow new satellites to begin researching new planets. [Request]

### ISSUE THREAD

**Issue by DJJBanx** [MJRLegends/Planet-Progression#30]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

Currently, when you launch a new satellite, it immediately begins to research the Moon. However, if you have already launched a satellite and have already researched the moon, then there is no point in researching the moon again. My request is to make it so that newly launched satellites begin to research planets that you have not discovered yet so that time and resources aren't wasted when launching multiple satellites.

Forge: 14.23.4.2708
Micdoodle-Core: 4.0.1.181
Galacticraft-Core: 4.0.1.181
Galacticraft-Planets: 4.0.1.181
MorePlanets: 2.0.15-GC181
PlanetProgressions: 0.2.5

**Comment by MJRLegends** [comment]
Its setup so it will do a few planets but yeah you need to put them in the telescope as you go. This is due to how its coded and i dont think i can do it differently

**Comment by MJRLegends** [comment]
I'll keep the comments in mind though thanks
