### ISSUE TITLE
Question: Research compatibility to More Planets' Planets

### ISSUE THREAD

**Issue by IcedReaper** [MJRLegends/Planet-Progression#32]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
I would like to know if you already have added support for More Planets' Planets as I don't see their Research Papers in JEI and can't see them in the Space Map.
In a creative game I added all Research Papers I could find in JEI to telescope to see what is discovered.
I could see the Star of More Planet, but not the planets itself.
Did I miss a step, is it not yet implemented, or may it be a bug?

### Steps to Reproduce Issue
1. Feed all research papers to the telescope
2. Check map.

**Crash log/Log (if applicable):** No crash

**Screenshots (if applicable):** 
Screenshot from Space Map: https://i.imgur.com/9yaWL5L.png

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 0.2.5

**Where did this bug happen:** Single Player (creative world for testing purposes)

### Additional Information
Installed Mods and their versions:
https://pastebin.com/griPTLMg

**Comment by IcedReaper** [comment]
I checked the version I have installed and it is already the latest More Planets version 2.0.15-GC181.
I also checked it again, but don't have the planet's now either.

I don't think there is a problem with the telescope, but somehow the research papers aren't created or shown in JEI.
I did a few more screenshots which hopefully will be able to help you.
https://imgur.com/a/SU9uEKI

If I understand the code of both projects correctly the research papers should be created like for the other planets and their moons.

I did another test where I tested skipping extra planets (now only with the mods Galacticraft, Galacticraft Planets, More Planets, Planet Progression and JEI) and I only had the research papers for the Galacticraft Planets (Moon, Mars, Venus, Asteroids, Mercury, Jupiter, Saturn, Uranus and Neptune).

**Comment by MJRLegends** [comment]
Yeah i think more planets is registering them wrong, i will talk to the developer and get it fixed

**Comment by MJRLegends** [comment]
I've messaged the more planets developer asking for this change but no reply as of yet. Your welcome to make a issue over at his issue tracker for this https://github.com/SteveKunG/MorePlanets/issues

The issue is: More Planets 1.12 version, registering of planets in the init stage. Which is a issue for my Planet Progression mod as im registering items based on registered planets which is done after the pre init event but before the init event.

**Comment by MJRLegends** [comment]
Ok no problem

**Comment by MJRLegends** [comment]
@IcedReaper should be fixed i believe more planets dev updating including the needed change i asked him to make to fix this issue

**Comment by IcedReaper** [comment]
Thanks for letting me know @MJRLegends. I'll try it out.
