### ISSUE TITLE
[1.12.2] Satellites disappear on player death

### ISSUE THREAD

**Issue by christofferson** [MJRLegends/Planet-Progression#34]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
When a player respawns all of their previously launched satellites disappear. 

### Steps to Reproduce Issue
1. Launch one or more satellites
2. Verify those satellites exist in the Satellite Controller
3. Die and respawn
4. Break and replace satellite controller
5. Verify that there are no satellites listed

**Crash log/Log (if applicable):** Not applicable

**Screenshots (if applicable):** Not applicable

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** PlanetProgression-1.12.2-0.2.6

**Where did this bug happen:** Server

### Additional Information
AFAIK it should be as simple as either copying the satellite list [here](https://github.com/MJRLegends/Planet-Progression/blob/1921829c76c46c11be3ac18f1514160e14fcb80e/src/main/java/com/mjr/planetprogression/handlers/capabilities/StatsCapability.java#L100) or specifically handling the copying of the satellite list [here](https://github.com/MJRLegends/Planet-Progression/blob/303145c004654329bb478f844edc19117720f8c4/src/main/java/com/mjr/planetprogression/handlers/MainHandlerServer.java#L76)

**Comment by MJRLegends** [comment]
Updates are rolling out to fix right now. Sorry for the delay
