### ISSUE TITLE
Creative ONLY issue: breaking telescope doesn't delete it

### ISSUE THREAD

**Issue by TheQuadShot** [MJRLegends/Planet-Progression#36]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]
In creative breaking a block will delete said block, the telescope doesn't though, it just drops as normal.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
PlanetProgression-1.12.2-0.2.9.jar

**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
I believe this is the same as the NASA workbench, and other GC related multi-block structures. I've come to the decision to keep mine the same and wont be fixing it, after finding this out about GC multi-block structures are the same way :D
