### ISSUE TITLE
strange, I have a giant telescope after trying to place one in a frame

### ISSUE THREAD

**Issue by TheQuadShot** [MJRLegends/Planet-Progression#37]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
[Description of the issue]

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

It's a bit dark, but the spheres are 55x55x55
https://imgur.com/72uf39l

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
PlanetProgression-1.12.2-0.2.9.jar

**Where did this bug happen:** [Single Player or Server]
I tried to put a telescope in a frame. I can't "find" it to break/delete it.
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Please completely fill out the issue report. Will reopen when you have done so
