### ISSUE TITLE
Telescope issues

### ISSUE THREAD

**Issue by DemonfangArun** [MJRLegends/Planet-Progression#38]
### ---Issue Report---
**(PLEASE DON'T DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**
OK there boss, that's not a good way to make people like your mod, but you do you >.>

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):**
Yes

### Description of Issue
Upon attempting to interact with the telescope after placing it, I got a conflict between it and another mod. After disabling the aforementioned other mod, I got another report spat out by Vanilla Fix of a conflict with another mod.

### Steps to Reproduce Issue
1-Place telescope
2-Attempt to interact with it

I'm not going to upload files to some random site, here are the files, notepad++ is a good suggestion for reading them (anyone modding minecraft should use this program).

Crash involving this mod and Dakimakura Mod:
[crash-2018-11-06_15.27.52-client.txt](https://github.com/MJRLegends/Planet-Progression/files/2555009/crash-2018-11-06_15.27.52-client.txt)

Non-crash involving this mod and Minecolonies
[crash-2018-11-06_15.47.06-server.txt](https://github.com/MJRLegends/Planet-Progression/files/2555011/crash-2018-11-06_15.47.06-server.txt)

**Version of Mod using (PLEASE DON'T USE 'Latest' OR 'Newest'):**
Forge 2768
Planet Progression 1.12.2-0.2.9
Dakimakura Mod 1.12.2-1.3
Minecolonies 1.12.2-0.10.27-Release

**Where did this bug happen:** [Single Player or Server]
Both

### Additional Information
The crash seems to be from this mod attempting to do something involving beds, at least from what I can make out. I can't think of why this would need to be a thing, it's effectively a giant machine block.

The second issue seems to be related.

**Comment by MJRLegends** [comment]
Please use pastebin for your crashlogs, it said dont upload the files in the part of the template you deleted *facepalm* i will reopen when you have updated it

**Comment by MJRLegends** [comment]
Ok no problem
