### ISSUE TITLE
[1.12.2] Placing the telescope crashes the game

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/Planet-Progression#4]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
Placing the telescope crashes the game.

### Steps to Reproduce Issue
1. Place a telescope

**Crash log/Log (if applicable):**
https://pastebin.com/BKFPJYiX

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.1

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/8sb1cg0H

**Comment by MJRLegends** [comment]
Already known

**Comment by MJRLegends** [comment]
Thanks for the bug report versions are rolling out now to fix this

**Comment by MJRLegends** [comment]
All been approved now
