### ISSUE TITLE
Planet progression screen flickering?

### ISSUE THREAD

**Issue by DragonHacker1** [MJRLegends/Planet-Progression#40]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
similar issues with that > #35 
### Description of Issue
[Description of the issue]
So i try to explain, tier 1 rocket or /dimensiontp cause screen flickering, alot, but unresearched things you will stuck forever on map with flickering, if i tried unlock all planets/moon for me will crash. I can provide more informations, but i don't know what specific informations want.
### Steps to Reproduce Issue
1. [First step] > Launch an rocket from overworld or a custommade dim with id 99 / use command /unlockAllCelestialBodies and launch an rocket from overworld or customade dim with id 99 
2. [Second step] Screen will flickering, but you don't have any option to launch or create because is not selected./ will flickering screen for some secs and crash.
**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
https://pastebin.com/XaDhj6UF
**Screenshots (if applicable):** 
I cannot provide screenshot, is just celestial map will flickering and if try to press overworld will get an option to create but the screen flickering too fast you cannot press.
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
PlanetProgression-1.12.2-0.3.0
**Where did this bug happen:** [Single Player or Server]
Same bug is visible on server ( no sponge or anything just default forge ) also singeplayer.
### Additional Information
[Any other information that may be able to help me with the problem]
Im only beta tester one on modpack, so i mainly focused on space, so i don't think an void world (custom map) will create the issue, i tested both on overworld also custom one. I tested removing planet progression mod seem working fine as okay. Please specify if is compability problem or .. Thank you for reading whole problem, p.s don't blame my languange.

**Comment by MJRLegends** [comment]
Try without galaxy space and its core mod

**Comment by DragonHacker1** [comment]
> Try without galaxy space and its core mod

That worked too well, so what should do? why this cause a problem? maybe i can suggest you make compability ?

**Comment by MJRLegends** [comment]
They need to add a way to disable their messing with the GuiCelestialSelection. And i dont support their mod as the mod dev ignored me for months when i wanted to add mod compact so i told him if they have to add the compact with my mods if they want it

**Comment by MJRLegends** [comment]
I think you can disable their galaxy map in the config of its core mod

**Comment by MJRLegends** [comment]
I might have a way to fix this from my side so planet progressions dont have to care about their galaxy map being disabled

**Comment by DragonHacker1** [comment]
I hope to make working, thank you time supporting this mod. Still i don't find the galaxy map to a way disable, i guess should open issue on galaxy map to add this support?

**Comment by MJRLegends** [comment]
After looking at it. I cant do anything but they could easily make to so if planet progression is loaded their galacy map disabled by i doubt they care to do that

**Comment by MJRLegends** [comment]
But yeah feel free to open a issue for galaxy space

**Comment by MJRLegends** [comment]
for future reference seems the solution is ```
disable GalaxyMap in configs/AsmodeusCore/core.conf

#Enable/Disable New Galaxy Map.
B:enableNewGalaxyMap=true
```

**Comment by DragonHacker1** [comment]
That fixed us problem, thank you for supporting.

**Comment by MJRLegends** [comment]
Duplicate of #33
