### ISSUE TITLE
Multiple research papers consumed when stacked in telescope

### ISSUE THREAD

**Issue by Blayyke** [MJRLegends/Planet-Progression#43]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Using research papers in the telescope will clear the entire slot rather than just deleting one item on research completion. Having multiple of the same type of research paper results in them all being deleted when it finishes.

### Steps to Reproduce Issue
1. Place 2 or more research papers of the same type in a telescope
2. Wait for telescope to finish
3. All of the research papers are gone, rather than just one

**Crash log/Log (if applicable):** None.
**Screenshots (if applicable):** Not super useful but
https://i.imgur.com/93MTY38.jpg, https://i.imgur.com/vsksmPi.jpg
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** PlanetProgression-1.12.2-0.3.1

**Where did this bug happen:** Single player, probably server too

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Are you stacking the research papers for the same planet/moon?

**Comment by Blayyke** [comment]
Yes, when research papers of the same planet are stacked in the telescope they all vanish when the research completes.

**Comment by Blayyke** [comment]
Oh right, ah well not much of an issue lol. thanks anyway :P

**Comment by MJRLegends** [comment]
Yeah haha i will fix it though as it is a bug. Thanks for the bug report.
