### ISSUE TITLE
Ticking Player Error

### ISSUE THREAD

**Issue by Vagueness** [MJRLegends/Planet-Progression#44]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
[With Planet Progression ( 1.12.2 )  installed, I can't land on planets or space-stations.
It will crash and say there was a ticking error whilst loading player - it only occurs with Planet Progression installed.]

### Steps to Reproduce Issue
1. [Load game with Optifine, Galacticraft, extra planets and planet progression.]
2. [Create satellite/space-station.]

**Crash log/Log (if applicable):** [N/A]
> *How do i locate a crash log* see https://docs.mjrlegends.com/Minecraft/crash-log/

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.12.2-0.3.2]

**Where did this bug happen:** [Single Player]

### Additional Information
[N/A]

**Comment by MJRLegends** [comment]
You talk about crashing but havent posted any crash logs.

Unfortunately we are only programmers and we have not been to magic school so your going to have to provide the info we cant read your mind or access your crash logs remotely

**Comment by Vagueness** [comment]
Here's the most recent crash report with Planet Progression installed.

[Planet Progression Crash Report.txt](https://github.com/MJRLegends/Planet-Progression/files/3085939/Planet.Progression.Crash.Report.txt)

**Comment by MJRLegends** [comment]
Please can you post a copy of your player data file

**Comment by Vagueness** [comment]
I believe these are the player data files.
They might be incorrect, given it's my first time diving deep into the .minecraft folder so please forgive any mistakes.

[Player data.txt](https://github.com/MJRLegends/Planet-Progression/files/3086044/Player.data.txt)
[Player data file 2.txt](https://github.com/MJRLegends/Planet-Progression/files/3086045/Player.data.file.2.txt)

**Comment by MJRLegends** [comment]
Idk what you sent me but them are not the player files

**Comment by Vagueness** [comment]
Those are what appeared in the player data folder after receiving the crash message.

**Comment by MJRLegends** [comment]
They should be named a bunch of random letters and numbers ending in .dat for the file type

**Comment by Vagueness** [comment]
This is the file.
I honestly don't know whats wrong with it, but it's the same as the last file I uploaded.

[63d9dd5b-a66b-4d21-b602-09dfebd4f041.txt](https://github.com/MJRLegends/Planet-Progression/files/3086224/63d9dd5b-a66b-4d21-b602-09dfebd4f041.txt)

**Comment by MJRLegends** [comment]
Thanks that one worked, idk why but the other ones were not lol

**Comment by Vagueness** [comment]
Ah, I’m glad that one worked. 
Hopefully that helps with the issue.

**Comment by MJRLegends** [comment]
will be fixed in the next update, thanks issue has been found

**Comment by Vagueness** [comment]
Glad to be of help. 
 Any estimate on when the update comes out ?

**Comment by MJRLegends** [comment]
Within the next 48 hours

**Comment by MJRLegends** [comment]
Updates for MC 1.12.2 and MC 1.11.2 have been released, MC 1.10.2 and MC 1.8.9 will be out soon

**Comment by Vagueness** [comment]
I’ll have a look tomorrow, keep up the good work.

**Comment by MJRLegends** [comment]
Update for MC 1.10.2 have been released

**Comment by MJRLegends** [comment]
Update have been released for MC 1.8.9
