### ISSUE TITLE
Allow ExtraPlanets Galaxy Map/Celestaial Selection Screen to be used

### ISSUE THREAD

**Issue by DevinPF** [MJRLegends/Planet-Progression#45]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 

Yes.

### Description of Issue
It's two fold:
1. When Planet-Progression and Extra Planets are both installed, Planet Progression seems to cause the +More button for the additional galaxies to disappear.

2. When you /unlockAllCelestialBodies, the planets from the extra galaxies will render inside the solar system.

### Steps to Reproduce Issue
1. Install both Extra Planets and PlanetProgression

2. Run the command and check the map

**Screenshots (if applicable):** 
Before running the command:
https://imgur.com/a/6Z4y2r1
After:
https://imgur.com/a/Jc1kJZb

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
PlanetProgression-1.12.2-0.3.4
ExtraPlanets-1.12.2-0.5.2

**Where did this bug happen:** Single Player

### Additional Information

Upon further testing, the stars from the other galaxies will appear in the sun even before running the command, however, the command causes the planets to show up, which aren't present before firing it. The stars are listed as members of the Milky Way Galaxy. When planet progression is uninstalled, this is not the case and they're appropriately classed.

**Comment by MJRLegends** [comment]
1. I cant fix this sorry
2. ExtraPlanets custom galaxies can be disabled via ExtraPlanets config

> Setting this option to false will disable & remove the Custom Galaxies on Celestaial Selection Screen (Note: Will get disabled by the 'Use Custom Galaxy Map/Celestaial Selection Screen' option)
>     B:"Custom Galaxies on Celestaial Selection Screen"=true
>

**Comment by MJRLegends** [comment]
Will be looking in to getting this to be a thing, think i have an idea

**Comment by MJRLegends** [comment]
Will be in the next mc 1.12.2 update and then the other mc versions soon

**Comment by MJRLegends** [comment]
Update are currently rolling out for MC 1.12.2, 1.11.2, 1.10.2. MC 1.8.9 will come later

**Comment by MJRLegends** [comment]
Update have been released for MC 1.8.9
