### ISSUE TITLE
Sevrer crash when placing hopper beneath Satellite Controller

### ISSUE THREAD

**Issue by SonicSpeedster16** [MJRLegends/Planet-Progression#46]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Placing a hopper beneath a Satellite Controller results in a unrecoverable Ticking block entity crash loop on a server.

### Steps to Reproduce Issue
1. Launch Satellite(s) into space
2. Begin researching using the Satellite Controller.
3. Place a hopper beneath the Satellite Controller in order to collect research papers.

**Crash log/Log (if applicable):** https://pastebin.com/04Ab2jNm

**Screenshots (if applicable):** N/A

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.3.5

**Where did this bug happen:** Server

### Additional Information
Playing the Minecraft 1.12.2 modpack "Star Tech" using Forge 14.23.5.2836 on a private server.

**Comment by MJRLegends** [comment]
Update have been released for MC 1.12.2, 1.11.2, 1.10.2, MC 1.8.9 will come later

**Comment by MJRLegends** [comment]
Update have been released for MC 1.8.9
