### ISSUE TITLE
Missing Lang and textures

### ISSUE THREAD

**Issue by TheRealM18** [MJRLegends/Planet-Progression#49]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes
### Description of Issue
[Description of the issue]
After Research Page 70, if gots to unknown lang and textures.
### Steps to Reproduce Issue
1. Get 71 research planets
2. look in the creative tab

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
http://prntscr.com/plbwpt
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.3.8
**Where did this bug happen:** [Single Player or Server]
Singleplayer
### Additional Information
[Any other information that may be able to help me with the problem]
if you need a enough mods to test it i can provide a pack for you. (and it is only 81 mods and max of 2GBs)

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak, MC 1.8.9 had this fixed already in v0.2.7
