### ISSUE TITLE
[1.12.2] Parachute doesn't open when satellite is launched into space

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/Planet-Progression#5]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
If a satellite is launched in a satellite rocket the parachute doesn't open when the player drops at y=1200, falling down  without it isn't fun :smile:
Also I didn't got the rocket nor the launch pad back, is this intentional?

### Steps to Reproduce Issue
1. Launch a satellite rocket and wait until y=1200

**Crash log/Log (if applicable):**
No crash

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.1

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/8sb1cg0H

Thanks for the mod btw. :smiley:

**Comment by MJRLegends** [comment]
intended

**Comment by MJRLegends** [comment]
Thanks for the report though i will see what i can change for this in the future
