### ISSUE TITLE
Option to disable message shown upon first joining world or server

### ISSUE THREAD

**Issue by SebaSphere** [MJRLegends/Planet-Progression#50]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
Upon loading a world or joining a server for the first time, message appears saying "You have discovered Earth"

Would be nice if there was a option to disable this

### Steps to Reproduce Issue

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/27737877/70491069-2e43c580-1ace-11ea-90f8-ba9fffdf0d30.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
PlanetProgression-1.12.2-0.3.8.jar
MJRLegendsLib-1.12.2-1.1.9.jar
forge-14.23.5.2847
GC Build 4.0.2.238

**Where did this bug happen:** [Single Player or Server]
SP and SMP
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Will be in the next updates

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak
