### ISSUE TITLE
Satellite Controller & Telescope picking up already researched planets/moons

### ISSUE THREAD

**Issue by xJon** [MJRLegends/Planet-Progression#52]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Research paper "Overworld" exists?

### Steps to Reproduce Issue
1. Launch 5 satellites 
2. The 5th one will provide "Overworld" research paper
3. Trying to use it in the telescope keeps resetting and not working 

**Screenshots (if applicable):**
![Screenshot_1](https://user-images.githubusercontent.com/8945347/72574434-b6896780-38d1-11ea-8a56-86c6433d0ce8.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** `0.3.9`

**Where did this bug happen:** [Single Player]

**Comment by MJRLegends** [comment]
1. Satellite Controler picking up already researched issue fixed... No idea how this wasn't found before and idk why was like this xD i defo made it not do this ages ago..

2. Telescope running when putting in a already researched paper been fixed

**Comment by MJRLegends** [comment]
Updates are being released as we speak for MC 1.8.9 - 1.12.2

**Comment by RowanSonder** [comment]
Did this go in to the 0.4.1 release? Currently have an issue where my satellite controller flicks between Mercury and Io, both of which I have discovered in the telescope. It won't move on to my next undiscovered planet, Ganymede.
