### ISSUE TITLE
Researching the papers in the telescope finishes at 50%

### ISSUE THREAD

**Issue by xJon** [MJRLegends/Planet-Progression#53]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Researching the papers in the telescope finishes at 50%

### Steps to Reproduce Issue
1. Put a research paper into the telescope 
2. See that it finishes at 50% and not 100%

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** `0.3.9`

**Where did this bug happen:** [Single Player]

**Comment by xJon** [comment]
[latest.log](https://github.com/MJRLegends/Planet-Progression/files/4074584/latest.log)
That is my latest client log, is anything else necessary?

**Comment by MJRLegends** [comment]
Thanks so does it actually work even tho it gets to 50% not 100%?

**Comment by MJRLegends** [comment]
Having a very hard time reproducing or seeing a issue in code that would cause this.. please can you test in a new world. or is the any other triggers you can think of what got you to this point

**Comment by xJon** [comment]
@MJRLegends I just remember I did disable the overworld message in the config. Would that be it?

**Comment by MJRLegends** [comment]
Will take a look again later see if i can reproduce the error..

**Comment by xJon** [comment]
@MJRLegends Thank you!

**Comment by xJon** [comment]
![bug2](https://user-images.githubusercontent.com/8945347/72671284-8fa56f80-3a50-11ea-9de2-e21b58205a6e.gif)

**Comment by xJon** [comment]
I can confirm the dev version resolves the issue in my world.

**Comment by MJRLegends** [comment]
Updates are being released as we speak for MC 1.8.9 - 1.12.2
