### ISSUE TITLE
Changing satellite IDs to show custom names?

### ISSUE THREAD

**Issue by xJon** [MJRLegends/Planet-Progression#54]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
It might be nice if instead of showing the players the long satellite UUIDs there could be a satellite renaming option, so players could put 

First of all, I think that if there is only one satellite it should be called Satellite and not Basic Satellite - it's kind of condescending

Then, players could rename it in an anvil so it will show the custom names of the satellites they launched in the satellite controller.
If players choose not to, then maybe it could show some sort of a trimmed ID? Just anything that would look better in chat & in the GUI.

Thank you!

**Screenshots (if applicable):** 
![Screenshot_2](https://user-images.githubusercontent.com/8945347/72574740-c6557b80-38d2-11ea-8ab5-7e399cf6be20.png)
![Screenshot_1](https://user-images.githubusercontent.com/8945347/72574741-c6557b80-38d2-11ea-8780-09137c82d7c8.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [`0.3.9`]

**Where did this bug happen:** [Single Player]

**Comment by MJRLegends** [comment]
I plan to do a lot more with this addon but my motivation has gone a bit hopefully i will get back in to the extra features i had in mind

**Comment by MJRLegends** [comment]
Added for next update
![](https://i.gyazo.com/c6b8f470c2fb2a762b8d0c220a180725.png)
![](https://i.gyazo.com/d93e7fff74f8de2b086dc0741d6fc9e0.png)

**Comment by MJRLegends** [comment]
Updates are being released as we speak for MC 1.8.9 - 1.12.2
