### ISSUE TITLE
Visual Client Desync issue when opening Satellite Rocket GUI after loading satellites

### ISSUE THREAD

**Issue by xJon** [MJRLegends/Planet-Progression#55]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Cargo Loader cannot be used for auto launching rockets.
In fact, placing a rocket manually and then putting satellites in the cargo loader just makes them to disappear instead of going into the rocket's cargo.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** `0.3.9`

**Where did this bug happen:** [Single Player]

**Comment by MJRLegends** [comment]
Fix found :D will be in next update

**Comment by xJon** [comment]
This is using `0.4.0-DEV`:
![bug](https://user-images.githubusercontent.com/8945347/72685099-6556bf00-3aef-11ea-97b4-212e0afeb1db.gif)

**Comment by MJRLegends** [comment]
Turns out to be a Galacticraft issue, as the cargo rocket has the same issue
