### ISSUE TITLE
Satellite controller antenna?

### ISSUE THREAD

**Issue by xJon** [MJRLegends/Planet-Progression#56]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Would be cool if one had to connect the appropriate antenna in order for the satellite controller to work and communicate with all launched satellites:
![](http://hackaday.com/wp-content/uploads/2014/04/effelsberg.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [`0.3.9`]

**Comment by MJRLegends** [comment]
How does this look, it uses the Communications Dish from Galacticraft @xJon >?
![](https://i.gyazo.com/0622d7f9449cfefe181ddd24642262d6.png)

**Comment by MJRLegends** [comment]
![](https://i.gyazo.com/2aa8a5a0174ce24b3b5dfa6d6d20ee01.png)

**Comment by xJon** [comment]
@MJRLegends That looks super cool! I wasn't aware of the Communications Dish from Galacticraft.
Reading the wiki, it says that it doesn't even have a use, so this is somehow even better.

**Comment by MJRLegends** [comment]
Still working on a better system before this is fully add :P

**Comment by MJRLegends** [comment]
Updates are being released as we speak for MC 1.8.9 - 1.12.2
