### ISSUE TITLE
Satellite Controller can research moons before their planets

### ISSUE THREAD

**Issue by xJon** [MJRLegends/Planet-Progression#57]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
The Satellite Controller can research moons before their planets, which makes them not appear in the map.
Video: https://i.imgur.com/z2kjDOV.mp4

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [`0.3.9`]

**Where did this bug happen:** [Single Player]

**Comment by xJon** [comment]
This seem to work.
So after one would research planet x then they would have to launch other satellites and it will let planet x's moons to be researched?

**Comment by MJRLegends** [comment]
No once a planet is researched and unlocked the satellite will just have a chance of picking a moon to research

**Comment by xJon** [comment]
Can you then please make it so it will specify in the controller not only the moon's name but also the moon's planet's name? Just so players will have more context

**Comment by MJRLegends** [comment]
Maybe

**Comment by MJRLegends** [comment]
Updates are being released as we speak for MC 1.8.9 - 1.12.2
