### ISSUE TITLE
Satellite Controller showing unlocalized names ExtraPlanets planets/moons

### ISSUE THREAD

**Issue by xJon** [MJRLegends/Planet-Progression#58]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
- The Satellite Controller `Researching` line has some wrong text for some planets/moons:
![bug](https://user-images.githubusercontent.com/8945347/72684840-b2856180-3aec-11ea-8b72-886793332319.gif)

- It says `Researching : <name>` with a space after `Researching`.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [`0.4.0-dev`]

**Where did this bug happen:** [Single Player]

**Comment by MJRLegends** [comment]
Very weird means they are not getting localized

**Comment by MJRLegends** [comment]
Updates are being released for MC 1.8.9 - 1.12.2
