### ISSUE TITLE
[1.12.2] Wierd Telescope+Battery dehaviour

### ISSUE THREAD

**Issue by DevTimur** [MJRLegends/Planet-Progression#59]
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes.

### Description of Issue
Depending on battery type (Nornal, Infinite, Creative) you get different completion percent in Telescope.
https://i.gyazo.com/3a1ad6647c73dc92d516259db7ec2083.gif

**Version of Mod using:** PlanetProgression-1.12.2-0.4.0

**Where did this bug happen:** Single Player

**Comment by MJRLegends** [comment]
Updates are being released as we speak for MC 1.8.9 - 1.12.2
