### ISSUE TITLE
[1.12.2] Scrolling through satellites in satellite controller doesn't work

### ISSUE THREAD

**Issue by wamc2017** [MJRLegends/Planet-Progression#6]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** yes

### Description of Issue
I launched three satellites currently but can't scroll through them in the satellite controller (seems like the buttons doesn't work), is this intended, because I haven't progressed further?

### Steps to Reproduce Issue
1. Launch two or more satellites and try to scroll through them in the satellite controller.

**Crash log/Log (if applicable):**
No crash

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.1.1

**Where did this bug happen:** Single Player

### Additional Information
Modlist: https://pastebin.com/8sb1cg0H

**Comment by MJRLegends** [comment]
yeah replace them machine to load them

**Comment by wamc2017** [comment]
Already tried replacing it, but makes no difference... ;)

**Comment by MJRLegends** [comment]
You need to put the satellite in the cargo on the rocket, and you need to fly it up and if you get a chat message then its worked if not its not launched it
