### ISSUE TITLE
[BUG?] Telescope accept batteries, but don't drain them

### ISSUE THREAD

**Issue by DevTimur** [MJRLegends/Planet-Progression#60]
### ---Issue Report---
**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yeap!

### Description of Issue
I use "What's this slot?" mod, it shows every items you can insert in slot (See screenshot), and I can insert other mod's battery in, but it's not draining. Can you possibly make so any RF (FE) battery would be accepted. I need it for modpack reasons. If you like make it configurable option, if it break your immersion.

**Screenshots (if applicable):** 
https://i.gyazo.com/e6bc369e37a07b401eafad1dd909fd4a.gif

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
PlanetProgression-1.12.2-0.4.1
**Where did this bug happen:** [Single Player or Server]
Singleplayer
### Additional Information
Request: Add support for ANY battery with RF (Forge) energy.

**Comment by MJRLegends** [comment]
What mod are these batteries from that you are having issues with?

**Comment by DevTimur** [comment]
Well, basically any mod's battery.
For example Tech Reborn battery, and energy crystals. Or Magneticcraft sulfuric battery (It use Forge Energy), or Matter Overdrive battery. Really i can't even insert them. But i CAN insert Tesla mod's battery, and it's not draining.

I can understand your intention to use Telescope without external power source (Tho, it's a bit inconvinient), but why I can't insert ANY battery exept orginial GC ones? This looks wierd, imho.

**Comment by MJRLegends** [comment]
Items dont have Forge Energy only tile entities do. And Galacticraft handles all power systems for my mod, so its a matter of supporting each mods battery power system

**Comment by MJRLegends** [comment]
Meaning Galacticraft machines wont accept any of the batteries you listed. Please report to Galacticraft that their item power system doesnt support the batteries you listed

**Comment by MJRLegends** [comment]
Also I believe batteries have a different system to tile entities so things like RF and FE dont actually exist for batteries they tend batteries tend to use their own system

**Comment by MJRLegends** [comment]
For batteries Galacticraft only supports for batteries its own/mekanism/IC2 for some reason others have not been added yet  or are commented out
