### ISSUE TITLE
Option to disable research papers by name or ID 

### ISSUE THREAD

**Issue by SomethingSomethingDarkside3** [MJRLegends/Planet-Progression#61]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
YES
### Description of Issue
[Description of the issue]
Add config option to disable research paper for any planet by name or dim ID (if your server has id's that are not default)

You can remove papers from worldgen and structures, but if your using the system where those methods to obtain the papers is not used (ie: satellites) then there is no method to remove papers.
### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
0.4.1
**Where did this bug happen:** [Single Player or Server]

### Additional Information
[Any other information that may be able to help me with the problem]
This would make certain planets from being able to be unlocked unless some custom implementation was made, mainly multiplayer servers and would generally give it more flexibility to use the mod if one needed or wanted too. (ie: if you have BlankPlanet installed, it says you unlocked that planet also on first login and that cannot be removed)

**Comment by MJRLegends** [comment]
Im adding the following option for the next update, i think this should cover your suggestion? let me know if if it doesnt

![](https://i.gyazo.com/b42235775aa68901a176147e03118285.png)

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak to include above config option i posted image of above
