### ISSUE TITLE
Satellite recipe with CraftTweaker shows in JEI but wouldn't build

### ISSUE THREAD

**Issue by SomethingSomethingDarkside3** [MJRLegends/Planet-Progression#62]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
YES
### Description of Issue
[Description of the issue]
when adding a custom Basic Satellite recipe via CraftTweaker, it shows as it should in JEI, however when adding the items into the builder, it just sits at IDLE and doesn't craft.

Followed the help article on your Wiki, unless i still missed something the 10 times i read over which if i did, then i do apologize. 

### Steps to Reproduce Issue
1. create custom satellite recipe .zs file with crafttweaker
2. load minecraft
3. add items
4. watch as custom recipe doesnt craft

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
**zs script** --> https://hastebin.com/lupumiqaja.css
**crafttweaker.log (showing script loading)** --> https://hastebin.com/zinoxevive.md

**Screenshots (if applicable):** 
[JEI Showing Custom Recipe / Default recipe removed](https://i.imgur.com/90ur1p1.jpg)
[Recipe Showing IDLE](https://i.imgur.com/52qL9V3.jpg)
**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
PlanetProgressions 0.4.1
**Where did this bug happen:** [Single Player or Server]

### Additional Information
CraftTweaker v4.1.20
Forge 14.23.5.2847

**Comment by MJRLegends** [comment]
Seems to work with a very basic recipe(see below) maybe its to do with amounts or item damage thats the issue i will look in to it

![](https://i.gyazo.com/d3134af5e9e4e30c9c866a948924ae68.png)
![](https://i.gyazo.com/da301ea7a6c150e1c3854e60c77374e2.png)

**Comment by MJRLegends** [comment]
Seems to all work on, i see your issue tho. 

You have put in <galacticraftcore:basic_item:12> (Blue Solar Waffer) rather than what you added via craft tweaker which was <galacticraftcore:basic_item:1> (Full Solar Panel)

Let me know if you have any more issues
