### ISSUE TITLE
Satellite Controller Researches Previously Discovered Planets with ExtraPlanets

### ISSUE THREAD

**Issue by RowanSonder** [MJRLegends/Planet-Progression#64]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes #52 is closest but I still have an issue

### Description of Issue
Satellite controller alternates between researching Mercury and Jupiter despite the fact I've discovered them both in the telescope. My next planet Ceres, doesn't get researched by the controller.

I do remember that I discovered Jupiter before any other planet from a chest paper so i suspect that may be the issue.

### Steps to Reproduce Issue
1. Discover planet from chest paper
2. Progress to that planet with controller and no further planets are discovered

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82
> *How do i locate a crash log on Minecraft on FTB? see* http://imgur.com/a/IbWNC
N/A
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.4.1
**Where did this bug happen:** [Single Player or Server]
Server
### Additional Information
[Any other information that may be able to help me with the problem]

I did notice what I thought was the same problem where the controller alternated between Mercury and Io however I hadn't discovered Io in the telescope yet. The controller then start working again but it would research Mercury every other planet (Ganymede -> Mercury -> Europa -> Mercury -> Callisto -> Mercury -> Jupiter)

I've triple checked that I have discovered Jupiter in the telescope and as I mention I unlocked it from a chest paper.

**Comment by MJRLegends** [comment]
Please can you include a log file and if possible a single player world that has this issue for you

**Comment by RowanSonder** [comment]
So I was curious and did some investigation. 

In my player DAT file I noticed Mercury and Jupiter are stored as 'planet.Mercury' and 'planet.Jupiter' but you add them to the static researchPapers variable in PlanetProgression_Items as 'planet.mercury' and 'planet.jupiter'.

I think this causes `temp.contains(newName)` to incorrectly return false on lines 263 and 274 of TileEntitySatelliteController due to the casing difference.

I couldn't see why Mercury and Jupiter were capitalised but I guess all the extra planets names will be stored like this. 

The only thing is I would expect this issue to affect everyone. I'll try and test this tomorrow.

**Comment by MJRLegends** [comment]
Please provide the things i requested, i respect your trying to help but all i need is that them things i requested

**Comment by RowanSonder** [comment]
Not sure which log file you want as there is no crash report or anything. Here is a world with the issue. (It's from The 1.12.2 Pack)

[PlanetProgressionTest.zip](https://github.com/MJRLegends/Planet-Progression/files/4257325/PlanetProgressionTest.zip)

**Comment by MJRLegends** [comment]
Just the normal latest.log please

**Comment by RowanSonder** [comment]
[latest.log](https://github.com/MJRLegends/Planet-Progression/files/4263185/latest.log)

**Comment by DeadlySoren** [comment]
Hey I just wanted to comment and say that I have the exact same issue. Right down to it being Mercury and Jupiter as well. Once I had researched mercury every second research was Mercury again it took a lot longer to research planets but after I got Jupiter it got stuck in a loop and now I can't progress at all.

**Comment by MJRLegends** [comment]
Updates are rolling out as we speak to fix this
