### ISSUE TITLE
Hope to modify zh_CN.lang 

### ISSUE THREAD

**Issue by GuanCangHai6** [MJRLegends/Planet-Progression#65]
[zh_CN.zip](https://github.com/MJRLegends/Planet-Progression/files/4257063/zh_CN.zip)
Please modify this 'zh_cn.lang',thanks.
(My english is poor, i'm sorry)

**Comment by MJRLegends** [comment]
Thank you

**Comment by Qian-quan** [comment]
> Thank you
This is an interesting mod!
Can I advertise this mod to Chinese Minecraft Forum MCBBS?
Hope for your reply

**Comment by MJRLegends** [comment]
Nope

**Comment by Qian-quan** [comment]
Ummm....
I'll NEVER claim it as mine, I just wanna translate it and let more people know it,so why not?

**Comment by Qian-quan** [comment]
> Nope

Ummm....
I'll NEVER claim it as mine, I just wanna translate it and let more people know it,so why not?

**Comment by MJRLegends** [comment]
Translation added to mod for next update, Thank you
