### ISSUE TITLE
Satellites repeating planets

### ISSUE THREAD

**Issue by Jturtlz** [MJRLegends/Planet-Progression#66]
### Description of Issue
I'm playing in the 1.12.2 pack, and the satellites seem to be repeating the same three planets to research: Jupiter, Ceres and Mercury. I still have yet to unlock Saturn, as well as some others in other galaxies. Is this a glitch? Or do I need to send satellites up on another planet or something? Or has this been fixed and they haven't updated the pack? Thanks.

### Steps to Reproduce Issue
1. I sent two satellites up, and followed the steps to link the controller to the dish. Other than that I've just been using the controller as you normally would.

**Version of Mod using** Not sure, whatever is in The 1.12.2 Pack.

**Where did this bug happen:** Playing on a server with friends.

### Additional Information
Thanks for your time!

**Comment by MJRLegends** [comment]
Are you putting the research paper in the telescope as you go?

**Comment by Jturtlz** [comment]
Yes I have been.

**Comment by MJRLegends** [comment]
Please can you send me a copy of your player file

**Comment by Jturtlz** [comment]
Sure. Could you tell me where to go to find that?

**Comment by Jturtlz** [comment]
Here's a link to the file; this message box won't let me upload a DAT file.
[https://gofile.io/?c=Vp96DY](url)

**Comment by MJRLegends** [comment]
What version of The 1.12.2 Pack are you using

**Comment by Jturtlz** [comment]
Version 1.1.1

**Comment by MJRLegends** [comment]
Ok i believe this pack is using a out dated version of PlanetProgressions so in the next pack update out very soon maybe even today. This should be fixed in that pack update. 

Please test the pack update when the pack dev updates it and let me know if your problem gets fixed by that

**Comment by Jturtlz** [comment]
Will do!

**Comment by Jturtlz** [comment]
Pack update came out, and everything is working now!

**Comment by MJRLegends** [comment]
Woo nice
