### ISSUE TITLE
[1.12.2] Game is crashing when opening the Planetary View

### ISSUE THREAD

**Issue by LinuxSquare** [MJRLegends/Planet-Progression#68]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Game is crashing when opening the Planetary View with `ClassNotFoundException`:
```
Caused by: java.lang.ClassNotFoundException: com.mjr.extraplanets.client.gui.screen.CustomCelestialSelection
```

### Steps to Reproduce Issue
1. Create a new Map
2. Press `M` to open the Planetary View

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

https://paste.ubuntu.com/p/ZFRFbRjXN8/

**Screenshots (if applicable):** 
None

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):**
* MJRLegendsLib-1.12.2-1.1.9
* PlanetProgression-1.12.2-0.4.3

**Where did this bug happen:** [Single Player or Server]
Single Player

### Additional Information
Additional installed mods:
* forge-1.12.2-14.23.5.2847-universal
* CaveGenerator-0.16
* Galacticraft-Planets-1.12.2-4.0.2.272
* GalacticraftCore-1.12.2-4.0.2.272
* MicdoodleCore-1.12.2-4.0.2.272
* jei_1.12.2-4.15.0.291

System Info:
* MC-Version: 1.12.2
* Java-Version: `jre8-openjdk 8.u242-1`
* OS: Manjaro Linux x86_64
* Kernel: `5.5.19-1-MANJARO`
* CPU: Intel i7-4770 (8) @ 3.900GHz
* GPU: AMD ATI Radeon RX Vega 56/64
* GPU-Driver: `xf86-video-amdgpu` - Open Source
* RAM: 16GB
* Allocated RAM to Modpack: 5GB

**Comment by MJRLegends** [comment]
ExtraPlanets version?

**Comment by MJRLegends** [comment]
Ahh i see the issue the wrong import of a class has been made ok i will fix

**Comment by MJRLegends** [comment]
Update is rolling out as we speak to fix this issue, Thanks for reporting
