### ISSUE TITLE
Some Galaxy Space planets are missing

### ISSUE THREAD

**Issue by Gandalf360one** [MJRLegends/Planet-Progression#69]
### ---Issue Report---

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):
Yes

### Description of Issue
Some Research papers are missing for some Galaxy Space planets

### Steps to Reproduce Issue
1. Use all existing Research Papers
2. Look at the Planet map
3. use the /unlockAllCelestialBodies <player> command
4. Look again on the Planet map and you will see that there are more planets now

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
I dont know if a link for the log file is also okay because it is too big for patebin.
https://www.dropbox.com/s/eybyad02saotd1p/latest.log?dl=0

**Screenshots (if applicable):** 
-

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
-GalaxySpace-1.12.2-2.0.13
-GalacticraftCore-1.12.2-4.0.2.262
-PlanetProgression-1.12.2-0.4.4

**Where did this bug happen:** [Single Player or Server]
Singelplayer. Dont know if this bug happens also in the Multiplayer

### Additional Information
Missing Planets:
-Ceres
-Haumea
-Kuiper Belt
-Pluto
-Ariel
-Callisto
-Charon
-Deimos
-Dione
-Enceladus
-Europa
-Ganymede
-Iapetus
-IO
-Mimas
-Miranda
-Oberon
-Phroteus
-Rhea
-Tethys
-Titan
-Titania
-Triton
-Umbriel

**Comment by MJRLegends** [comment]
Has any version has these planets and moons included?

**Comment by MJRLegends** [comment]
Please can you include a latest.log file as i think that will help me also

**Comment by Gandalf360one** [comment]
Not all planets. Galaxy Space is still not finished and there will be more planets added in the future

**Comment by MJRLegends** [comment]
No, i meant has these planets unlocked correctly in any other Galaxyspace versions

**Comment by Gandalf360one** [comment]
I dont know

**Comment by Gandalf360one** [comment]
added the latest.log

**Comment by MJRLegends** [comment]
Issue found will be fixed in next update for MC 1.12.2

**Comment by MJRLegends** [comment]
Seems to work ok for me which is weird

**Comment by MJRLegends** [comment]
Ahh ok i see the issue ummm geez ok i will have to spend sometime on this

**Comment by MJRLegends** [comment]
Ok its because GalaxySpace is registering its planets in the init stage rather than the pre init stage. they will have to change this to fix this issue

**Comment by MJRLegends** [comment]
I will message the GalaxySpace dev

**Comment by MJRLegends** [comment]
@Gandalf360one If you can please option a issue on their issue tracker too saying i said

> GalaxySpace is registering its planets in the init stage rather than the pre init stage. they will have to change this to fix this issue

**Comment by Gandalf360one** [comment]
ok
