### ISSUE TITLE
[1.8+] Satellite Rockets showing to many types of rockers in JEI support

### ISSUE THREAD

**Issue by EmosewaPixel** [MJRLegends/Planet-Progression#7]
### Description of Issue
 All Satellite Rockets, but the one that has 1 Chest in it have missing textures.

**Screenshots (if applicable):** 
![image](https://user-images.githubusercontent.com/25333164/36390768-6a341940-15a4-11e8-89eb-6cb956e1d0bd.png)
![image](https://user-images.githubusercontent.com/25333164/36390773-6cf92378-15a4-11e8-807c-e8c02ef9df26.png)
![image](https://user-images.githubusercontent.com/25333164/36390779-70499d46-15a4-11e8-892b-9c1ea9c027e8.png)
![image](https://user-images.githubusercontent.com/25333164/36390786-73f5f0d4-15a4-11e8-8832-4f1a8600454d.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.2

**Where did this bug happen:** Single Player

**Comment by MJRLegends** [comment]
Yeah this is intentional as there is only one satellite rocket but the jei support is showing all 4 types i will change the jei support for it

**Comment by EmosewaPixel** [comment]
Yeah, I was surprised that the one without a Chest was there and I remember that none of them were in the previous version.

**Comment by MJRLegends** [comment]
Yeah the jei support just needs tweaking its just a visual thing

**Comment by MJRLegends** [comment]
Versions are rolling out with this fixed :D
