### ISSUE TITLE
Unable to use the AsmodeusCore Galaxy Map/Celestaial Selection Screen

### ISSUE THREAD

**Issue by AC102** [MJRLegends/Planet-Progression#71]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue

There is the normal celestial map instead of the AsmodeusCore Galaxy Map when there is this mod (so the option B:"Use Custom Galaxy Map/Celestaial Selection Screen" on false do not change anything and players seem to not be able to join the server when this option is on true "fatal missing registry entries")

### Steps to Reproduce Issue

1. put B:"Use Custom Galaxy Map/Celestaial Selection Screen"=false in ExtraPlanets.cfg
(I think everything is explained above)

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 

(all planets are unlocked)
![image](https://user-images.githubusercontent.com/65914391/82836090-2b932c00-9ec6-11ea-9689-50d8363bc372.png)
![image](https://user-images.githubusercontent.com/65914391/82836346-9f353900-9ec6-11ea-973a-dd877c796edc.png)
![image](https://user-images.githubusercontent.com/65914391/82836546-f6d3a480-9ec6-11ea-8cb8-32511817e0d2.png)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]

PlanetProgression-1.12.2-0.4.4

AsmodeusCore-1.12.2-0.0.15
GalacticraftCore-1.12.2-4.0.2.280
Galacticraft-Planets-1.12.2-4.0.2.280
ExtraPlanets-1.12.2-0.6.4
GalaxySpace-1.12.2-2.0.13
MJRLegendsLib-1.12.2-1.1.9

**Where did this bug happen:** [Single Player or Server]
Server 

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
AsmodeusCore Galaxy Map/Celestaial Selection Screen isnt compactbilty with Planet Progressions as they dont take in to account the has unlock check Planet Progressions needs via its api. So pointless me fixing in till they do that sorry.

**Comment by MJRLegends** [comment]
It should of crashed you with the message Please disable the following option: enableNewGalaxyMap in configs/AsmodeusCore/core.conf but they must of changed the name of and location of there class file for there screen
