### ISSUE TITLE
Server crash with cargo unloader & satellite rocket launch pad

### ISSUE THREAD

**Issue by CrasherCat** [MJRLegends/Planet-Progression#72]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
yes
### Description of Issue
[There's a repeatable server crash bug with this mod and galacticraft core, where upon placing a cargo unloader next to a satellite rocket launch pad, the server with instantly crash.  If you load the world up again after crashing, the world will stay up for a few seconds before crashing again.]

### Steps to Reproduce Issue
1. [First step]
Place Cargo Unloader (from galacticraft core) next to assembled(5x5) satellite rocket launch pad
2. [Second step]
Server should crash immediately after placement of cargo unloader.

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2-0.4.2
**Where did this bug happen:** [Single Player or Server]
Server & Single-Player

**Comment by MJRLegends** [comment]
You gotta include the crash log please for me to even help.

**Comment by MJRLegends** [comment]
I will reopen once crash log been posted

**Comment by MJRLegends** [comment]
Also the fact your using an old version is probably your issue also

**Comment by CrasherCat** [comment]
My bad, here's the crash log paste
https://pastebin.com/HGK6qMfc

**Comment by MJRLegends** [comment]
Update Planet Progressions your issue already fixed
