### ISSUE TITLE
Telescope Rendering Block Entity crash

### ISSUE THREAD

**Issue by SlappersOnly** [MJRLegends/Planet-Progression#73]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
If a telescope is placed down then people who log in within range of the telescope will crash.

### Steps to Reproduce Issue
1. Placed down telescope.
2. Someone tries to log in. Will successfully log in then instantly crash.
3. removed telescope and get them to log back in.
4. They successfully log in.
5. repeated steps 1 to 4 with someone else.

**Crash log/Log (if applicable):** https://pastebin.com/YHGWu4WB

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** 1.12.2-0.4.2

**Where did this bug happen:** Server

**Comment by MJRLegends** [comment]
You should be trying latest version before you report any bugs to make sure its not already fixed

**Comment by SlappersOnly** [comment]
I’ll have to wait for the “The 1.12.2 Pack” modpack to update to the newest version I guess.

They are still running the same version as the last bug report https://github.com/MJRLegends/Planet-Progression/issues/72 , which I’m not looking forward to testing if it crashes me as well.

**Comment by xJon** [comment]
@SlappersOnly Update `1.2.0` was released back at June 4th :)
