### ISSUE TITLE
research papers

### ISSUE THREAD

**Issue by Warbringer12** [MJRLegends/Planet-Progression#74]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
research papers gave wrong planet's when researched

### Steps to Reproduce Issue
1. gave self research paper jupiter but came up saturn
2. tried in multiple games same thing happened
3. tried unlocking all planets with /unlockAllCelestialBodies <player> didnt even work

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION] 1.12.2-0.4.4

**Where did this bug happen:** [Single Player or Server] single player

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Sorry for slow reply, how did you give your self the research paper?

**Comment by Warbringer12** [comment]
i pulled them from creative mode

**Comment by MJRLegends** [comment]
Are you able to show me a video of this as it cant reproduce it sorry

**Comment by Warbringer12** [comment]
yeah idk for some reason now i cant reproduce it but now the satellite controller doesn't give research papers even when i sent up a satellite and we have it set to the research mode of the basic satellite research method

**Comment by MJRLegends** [comment]
Please post more details video or/and screenshots of that new issue

**Comment by Warbringer12** [comment]
![2020-07-12_18 57 30](https://user-images.githubusercontent.com/44590540/87263585-76ff9a80-c472-11ea-9eee-2c3a9c21de01.png)
![2020-07-12_19 03 25](https://user-images.githubusercontent.com/44590540/87263586-77983100-c472-11ea-8f04-698a068b8bc0.png)

**Comment by MJRLegends** [comment]
Have you already unlocked every planet and moon?

**Comment by Warbringer12** [comment]
I did that experiment on a fresh world so no planets were unlocked at all. also launched the satellite in space

**Comment by MJRLegends** [comment]
Try clicking arrow buttons in satellite controller if that doesnt work try replacing that block

**Comment by Warbringer12** [comment]
already tried clicking arrow buttons and tried replacing the block it did nothing

**Comment by MJRLegends** [comment]
Ok please provided a log file showing you have launched a satellite you will get a message in chat saying its id once its launched and then please provide your player data file.

To me it looks like a satellite doesn't exist as a satellite id isn't even showing in the machine

**Comment by MJRLegends** [comment]
Guessing you solved it?
