### ISSUE TITLE
Crafting issue with Satellite Rocket when adding a chest to more than one slot

### ISSUE THREAD

**Issue by NeiRib** [MJRLegends/Planet-Progression#77]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes

### Description of Issue
I can't craft the Satellite Rocket

### Steps to Reproduce Issue
Playing?

**Screenshots (if applicable):** 
https://i.imgur.com/oeG0sGx.jpg

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
PlanetProgression-1.12.2 - 0.4.5

**Where did this bug happen:** [Single Player or Server]
Server

**Comment by MJRLegends** [comment]
Use only one chest
