### ISSUE TITLE
When using with Galaxy space, the game crashes after opening the galaxy map

### ISSUE THREAD

**Issue by q197990898** [MJRLegends/Planet-Progression#78]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
[Description of the issue]

When used with Galaxy space-1.12.2-2.0.14mod and the leading Asmodeus core-1.12.2-0.0.23 of Galaxy space, press M to open the galaxy map, the game crashes and an error report is generated.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/
[crash-2021-01-15_21.06.22-client.txt](https://github.com/MJRLegends/Planet-Progression/files/5820646/crash-2021-01-15_21.06.22-client.txt)
**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
PlanetProgression-1.12.2-0.4.5

**Where did this bug happen:** [Single Player or Server]
Single player and Server

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
java.lang.RuntimeException: Please disable the following option: enableNewGalaxyMap in configs/AsmodeusCore/core.conf
