### ISSUE TITLE
Add a dimension configuration that is unlocked by default

### ISSUE THREAD

**Issue by sddsd2332** [MJRLegends/Planet-Progression#83]
My English is not very good, so this is translated by Google.
I want to make an integrated package, but every time I join the world, I will unlock the Overworld. I want to make the default unlock for other dimensions.
The player starts from The Betweenlands, passes through The Twilight Forest, and finally reaches the Overworld. What do I need to configure?

**Comment by sddsd2332** [comment]
The corresponding configuration has been found, located in Galacticraft\core
     # Dimension ID for the Overworld (as seen in the Celestial Map)
     I:idDimensionOverworld=0
thanks

**Comment by MJRLegends** [comment]
Glad you solved it :)
