### ISSUE TITLE
Double Planets

### ISSUE THREAD

**Issue by Striker183** [MJRLegends/Planet-Progression#86]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes]

### Description of Issue
Hello, I have explored various planets via research paper. Now these are partially displayed twice both in the list on the left (see picture) and on their orbit. It's definitely not normal, maybe it's a known bug, if not then I've successfully registered it.

Greetings, Alex

### Steps to Reproduce Issue
1. Resarch a Planet (Jupiter)
2. Look at the Galaxymap

**Crash log/Log (if applicable): *No Crash*

**Screenshots (if applicable):** [Link (Lightshot)](https://prnt.sc/n-VO0j5jRL_i)

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [1.12.2-0.4.8]

**Where did this bug happen:** [Server]

### Additional Information
Used in Modpack "The 1.12.2 Pack - Perfectly Complex"

**Comment by MJRLegends** [comment]
This is a Galacticraft bug, as the red ones are being incorrectly added by their new version

https://github.com/TeamGalacticraft/Galacticraft-Legacy/commit/b1ae3d8e30f7144d28bdff9111100b46bef4f115
